yelp2018:
  name: SwAVGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.eps: 0.2
  model_config.num_layers: 3
  model_config.layer_cl: 1
  model_config.proto_reg: 0.0001
  model_config.temperature: 0.05
  model_config.num_clusters: 2000

iFashion:
  name: SwAVGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.num_layers: 3
  model_config.layer_cl: 1
  model_config.proto_reg: 0.0000001
  model_config.temperature: 0.05
  model_config.num_clusters: 2000

douban-book:
  name: SwAVGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.lambda: 0.2
  model_config.num_layers: 3
  model_config.proto_reg: 0.0000001
  model_config.temperature: 0.05
  model_config.num_clusters: 2000

amazon-kindle:
  name: SwAVGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.lambda: 0.2
  model_config.layer_cl: 1
  model_config.num_layers: 3
  model_config.proto_reg: 0.0000001
  model_config.temperature: 0.05
  model_config.num_clusters: 2000

ml-1M:
  name: SwAVGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 4096
  learning_rate: 0.002
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.lambda: 0.2
  model_config.num_layers: 3
  model_config.proto_reg: 0.0000001
  model_config.temperature: 0.1
  model_config.num_clusters: 2000
